# Generated by Django 4.0.1 on 2022-01-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
