# Generated by Django 4.0.1 on 2022-01-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_country",
                to="API.country",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_Membership",
                to="API.membership",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="queue",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_queue",
                to="API.queue",
            ),
        ),
    ]
